MODALITY = {
    'T1w': {'Contrast': 'T1', 'Intent':'Structural'},
    'T2w': {'Contrast': 'T2', 'Intent':'Structural'},
    'T1rho': {'Custom': 'T1rho'},
    'T1map': {'Contrast': 'T1', 'Intent':'Structural', 'Features': 'Quantitative'},
    'T2map': {'Contrast': 'T2', 'Intent':'Structural', 'Features': 'Quantitative'},
    'T2star': {'Contrast': 'T2*', 'Intent':'Structural'},
    'FLAIR': {'Custom': 'FLAIR'},
    'FLASH': {'Custom': 'FLASH'},
    'PD': {'Contrast': 'PD', 'Intent':'Structural'},
    'PDmap': {'Custom': 'PD-Map'},
    'PDT2': {'Contrast': ['PD', 'T2'], 'Intent':'Structural'},
    'inplaneT1': {'Contrast': 'T1', 'Intent':'Structural', 'Features': 'In-Plane'},
    'inplaneT2': {'Contrast': 'T2', 'Intent':'Structural', 'Features': 'In-Plane'},
    'angio': {'Custom': 'Angio'},
    'defacemask': {'Custom': 'Defacemask'},
    'SWImagandphase': {'Custom': 'SWI'},
    'bold': {'Intent': 'Functional'},
    'events': [{'Intent': 'Functional'}, {'Custom': 'Behavioral'}],
    'sbref': [{'Intent': 'Functional'}, {'Contrast': 'Diffusion', 'Intent':'Structural'}],
    'stim': [{'Intent': 'Functional', 'Custom': 'Stim'}, {'Custom': 'Stim'}],         # stimulus
    'physio': [{'Intent': 'Functional', 'Custom': 'Physio'}, {'Custom': 'Physio'}],     # physio
    'dwi': {'Contrast': 'Diffusion', 'Intent':'Structural'},
    'phasediff': {'Contrast': 'B0', 'Intent': 'Fieldmap'},
    'magnitude1': {'Contrast': 'B0', 'Intent': 'Fieldmap'},
    'magnitude2': {'Contrast': 'B0', 'Intent': 'Fieldmap'},
    'phase1': {'Contrast': 'B0', 'Intent': 'Fieldmap'},
    'phase2': {'Contrast': 'B0', 'Intent': 'Fieldmap'},
    'magnitude': {'Contrast': 'B0', 'Intent': 'Fieldmap'},
    'fieldmap': {'Contrast': 'B0', 'Intent': 'Fieldmap'},
    'epi': {'Contrast': 'B0', 'Intent': 'Fieldmap'},
}

